CREATE DATABASE BdDemo;

Use BdDemo;

CREATE TABLE Client (IdClient CHAR (36) NOT NULL,
Prenom VARCHAR (30) NOT NULL,
Nom VARCHAR (30) NOT NULL,
Email VARCHAR (50) NOT NULL,
MotDePasseHash VARCHAR (256) NOT NULL,
Description VARCHAR (256) NULL,
PRIMARY KEY (IdClient));

CREATE TABLE Adresse (IdAdresse VARCHAR (36) NOT NULL,
NumeroAppartement VARCHAR (5) DEFAULT NULL,
NumeroDeRue VARCHAR (5) NOT NULL,
NomDeRue VARCHAR (50) NOT NULL,
Ville VARCHAR (50) NOT NULL,
Province VARCHAR (30) NOT NULL,
CodePostal VARCHAR (7) NOT NULL,
IdClient VARCHAR (36) NOT NULL,
PRIMARY KEY (IdAdresse),
FOREIGN KEY (IdClient)
REFERENCES Client (IdClient)
ON UPDATE CASCADE ON DELETE NO ACTION);


CREATE TABLE Image (IdImage VARCHAR (36) NOT NULL,
Nom VARCHAR (120) NOT NULL,
IdClient VARCHAR (36) NOT NULL,
PRIMARY KEY (IdImage),
FOREIGN KEY (IdClient)
REFERENCES Client (IdClient)
ON UPDATE CASCADE ON DELETE NO ACTION);